
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moses
 */
public class PrisonerIndex extends javax.swing.JFrame {
    Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;

    /**
     * Creates new form PrisonerIndex
     */
    public PrisonerIndex() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPrisonerNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 0), 4), "Prisoner Index", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        txtPrisonerNo.setToolTipText("");
        txtPrisonerNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrisonerNoActionPerformed(evt);
            }
        });
        txtPrisonerNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrisonerNoKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Enter Prisoner ID ");

        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ID1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrisonerNo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogIn)
                .addGap(160, 160, 160))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrisonerNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogIn)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrisonerNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrisonerNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrisonerNoActionPerformed

    private void txtPrisonerNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrisonerNoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            con=Connect.ConnectDB();
            String sql= "select * from prisoners where PrisonerID= '" + txtPrisonerNo.getText() +  "'";
            try
            {
                if (txtPrisonerNo.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Matric Number","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
                pst=con.prepareStatement(sql);
                rs= pst.executeQuery();
                if (rs.next() ){
                    this.hide();
                    PrisonerHome frm=new PrisonerHome();
                    frm.setVisible(true);
                    String add1=rs.getString("PrisonerID");
                    frm.txtPrisonerID.setText(add1);
                    String add2=rs.getString("Fname");
                    frm.txtFirstName.setText(add2);
                    String add3=rs.getString("Mname");
                    frm.txtMiddleName.setText(add3);
                    String add4=rs.getString("Surname");
                    frm.txtLastName.setText(add4);
                    String add5=rs.getString("DOB");
                    frm.txtDOB.setText(add5);
                    String add6=rs.getString("Sex");
                    frm.txtSex.setText(add6);
                    String add7=rs.getString("Crime");
                    frm.txtCrime.setText(add7);
                    String add8=rs.getString("Prison");
                    frm.txtPrison.setText(add8);
                    String add9=rs.getString("Sentence");
                    frm.txtSentence.setText(add9);
                    String add10=rs.getString("Code");
                    frm.txtCode.setText(add10);
                    String add11=rs.getString("DOI");
                    frm.txtDOI.setText(add11);
                    String add12=rs.getString("Status");
                    frm.txtStatus.setText(add12);
                    
                }
                else{

                    JOptionPane.showMessageDialog(null, "Prisoner Information is Missing !","Access denied",JOptionPane.ERROR_MESSAGE);
                    txtPrisonerNo.setText("");
                    txtPrisonerNo.requestDefaultFocus();
                }
            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, e);

            }
        }
    }//GEN-LAST:event_txtPrisonerNoKeyPressed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
            con=Connect.ConnectDB();
            String sql= "select * from prisoners where PrisonerID= '" + txtPrisonerNo.getText() +  "'";
            try
            {
                pst=con.prepareStatement(sql);
                rs= pst.executeQuery();
                if (rs.next() ){
                    this.hide();
                    PrisonerHome frm=new PrisonerHome();
                    frm.setVisible(true);
                    String add1=rs.getString("PrisonerID");
                    frm.txtPrisonerID.setText(add1);
                    String add2=rs.getString("Fname");
                    frm.txtFirstName.setText(add2);
                    String add3=rs.getString("Mname");
                    frm.txtMiddleName.setText(add3);
                    String add4=rs.getString("Surname");
                    frm.txtLastName.setText(add4);
                    String add5=rs.getString("DOB");
                    frm.txtDOB.setText(add5);
                    String add6=rs.getString("Sex");
                    frm.txtSex.setText(add6);
                    String add7=rs.getString("Crime");
                    frm.txtCrime.setText(add7);
                    String add8=rs.getString("Prison");
                    frm.txtPrison.setText(add8);
                    String add9=rs.getString("Sentence");
                    frm.txtSentence.setText(add9);
                    String add10=rs.getString("Code");
                    frm.txtCode.setText(add10);
                    String add11=rs.getString("DOI");
                    frm.txtDOI.setText(add11);
                    String add12=rs.getString("Status");
                    frm.txtStatus.setText(add12);
                    
                }
                else{

                    JOptionPane.showMessageDialog(null, "Prisoner Information is Missing !","Access denied",JOptionPane.ERROR_MESSAGE);
                    txtPrisonerNo.setText("");
                    txtPrisonerNo.requestDefaultFocus();
                }
            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, e);

            }
    }//GEN-LAST:event_btnLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrisonerIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrisonerIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrisonerIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrisonerIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrisonerIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPrisonerNo;
    // End of variables declaration//GEN-END:variables
}
